apiVersion: apps/v1
kind: Deployment
metadata:
  name: crop-recommender-deployment
  labels:
    app: crop-recommender
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crop-recommender
  template:
    metadata:
      labels:
        app: crop-recommender
    spec:
      tolerations:
        - key: "CriticalAddonsOnly"
          operator: "Exists"
        - key: "karpenter.sh/disrupted"
          operator: "Exists"
          effect: "NoSchedule"
      containers:
        - name: crop-recommender
          image: 610495549917.dkr.ecr.eu-central-1.amazonaws.com/crop-recommender_k87:latest
          ports:
            - containerPort: 5000
          imagePullPolicy: Always
