apiVersion: v1
kind: Service
metadata:
  name: crop-recommender-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
spec:
  selector:
    app: crop-recommender
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer
