name: deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      # ✅ NEW: Setup QEMU
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      # ✅ NEW: Setup Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build, Tag, and Push Docker image to ECR
        env:
          IMAGE_URI: ${{ secrets.ECR_REPOSITORY }}
        run: |
          docker buildx build \
            --platform linux/amd64 \
            -t $IMAGE_URI:latest \
            --push .

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }} --region ${{ secrets.AWS_REGION }}

      - name: Deploy to EKS
        run: |
          kubectl set image deployment/${{ secrets.DEPLOYMENT_NAME }} \
          crop-recommender=${{ secrets.ECR_REPOSITORY }}:latest
          kubectl rollout status deployment/${{ secrets.DEPLOYMENT_NAME }}
